<?php

use App\Http\Controllers\Auth\AdminController;
use App\Http\Controllers\Auth\CustomerController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

// Default Laravel Auth Routes (generated by Laravel UI/Breeze)
Auth::routes(['verify' => true]);
Route::get('/', function () {
    return redirect('/login');
});

// Customer Registration Routes
Route::get('/register/customer', [CustomerController::class, 'showRegistrationForm'])->name('register.customer');
Route::post('/register/customer', [CustomerController::class, 'register'])->name('register.customer.submit');

// Admin Registration Routes
Route::get('/register/admin', [AdminController::class, 'showRegistrationForm'])->name('register.admin');
Route::post('/register/admin', [AdminController::class, 'register'])->name('register.admin.submit');

// Admin Login Routes
Route::get('/login/admin', [AdminController::class, 'showLoginForm'])->name('login.admin');
Route::post('/login/admin', [AdminController::class, 'login'])->name('login.admin.submit');

// Example protected route (only accessible after email verification)
Route::get('/home', function () {
    return view('home');
})->middleware(['auth', 'verified']);
